import {
    SiJavascript,
    SiTypescript,
    SiPython,
    SiCplusplus,
    SiPhp,
    SiSwift,
    SiKotlin,
    SiGo,
    SiRust,
    SiRuby,
    SiElm,
    SiScala,
    SiR,
    SiDart,
    SiElixir,
    SiClojure,
    SiHaskell,
    SiErlang,
    type IconType,
} from '@icons-pack/react-simple-icons';

export const popularLanguages: {[key: string]: IconType} = {
    JavaScript: SiJavascript,
    TypeScript: SiTypescript,
    Python: SiPython,
    'C++': SiCplusplus,
    PHP: SiPhp,
    Swift: SiSwift,
    Kotlin: SiKotlin,
    Go: SiGo,
    Rust: SiRust,
    Ruby: SiRuby,
    Elm: SiElm,
    Scala: SiScala,
    R: SiR,
    Dart: SiDart,
    Elixir: SiElixir,
    Clojure: SiClojure,
    Haskell: SiHaskell,
    Erlang: SiErlang,
};
