name: Check the Branch Name

run-name: Check the branch --> ${{ github.repository }} follows naming rules.

on:
  pull_request:
    type: [opened, reopened]

description: 'Checks the branch name, only branch names that start with refactor/, bugfix/, hotfix/, or feature/ are allowed'

jobs:
  check-branch-name-is-valid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        run: echo "Branch name is ${{ github.head_ref }}"

      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"

          if [[ ! $BRANCH_NAME =~ ^(feature|bugfix|hotfix)/[a-z0-9._-]+$ ]]; then
            echo ":( Invalid branch name: $BRANCH_NAME"
            exit 1
          else
            echo ":) Branch name is valid: $BRANCH_NAME"
          fi

